#!/usr/bin/env python3
"""Encode the first Japanese-to-Chinese porting batch for the injected ROM."""

from __future__ import annotations

import ast
import json
import re
import sys
import warnings
from pathlib import Path


CHARMAP_RE = re.compile(r"^('(?:[^'\\]|\\.)*')\s*=\s*((?:[0-9A-Fa-f]{2}\s*)+)(?:@.*)?$")

CONTROLS = {
    "PLAYER": bytes((0xFD, 0x01)),
    "STR_VAR_1": bytes((0xFD, 0x02)),
    "STR_VAR_2": bytes((0xFD, 0x03)),
    "JPN": bytes((0xFC, 0x15)),
    "ENG": bytes((0xFC, 0x16)),
}

SYNTHETIC_PUNCTUATION = {
    "；", "。", "～", "、", "，", "！", "？", "：", "—", "“", "”", "…"
}


def read_charmap(path: Path) -> dict[str, bytes]:
    result: dict[str, bytes] = {}
    warnings.filterwarnings("ignore", category=SyntaxWarning)
    for line in path.read_text(encoding="utf-8").splitlines():
        match = CHARMAP_RE.match(line.strip())
        if not match:
            continue
        char = ast.literal_eval(match.group(1))
        encoded = bytes.fromhex(match.group(2))
        result.setdefault(char, encoded)
    return result


def encode_char(char: str, charmap: dict[str, bytes]) -> bytes:
    if char == "\n":
        return bytes((0xFE,))
    encoded = charmap.get(char)
    if encoded is None:
        raise ValueError(f"character missing from charmap: {char!r}")
    if char in SYNTHETIC_PUNCTUATION:
        if len(encoded) != 1:
            raise ValueError(f"punctuation must have a one-byte source glyph: {char!r}")
        return bytes((0x7F, encoded[0]))
    if len(encoded) == 2 and 0x01 <= encoded[0] <= 0x1E:
        if encoded[0] in (0x06, 0x1B) or encoded[1] > 0xF6:
            raise ValueError(f"invalid Chinese source encoding for {char!r}: {encoded.hex(' ')}")
        return bytes((encoded[0] + 0x5F, encoded[1]))
    if len(encoded) == 1:
        return encoded
    raise ValueError(f"unsupported encoding for {char!r}: {encoded.hex(' ')}")


def encode_text(text: str, charmap: dict[str, bytes], styled: bool) -> bytes:
    output = bytearray()
    if styled:
        # DrawOptionMenuChoice changes bytes 2 and 5 for the selected color.
        output.extend((0xFC, 0x01, 0x06, 0xFC, 0x03, 0x07))
    output.extend(CONTROLS["ENG"])

    index = 0
    while index < len(text):
        if text.startswith("\\p", index):
            output.append(0xFB)
            index += 2
            continue
        if text.startswith("\\l", index):
            output.append(0xFA)
            index += 2
            continue
        if text[index] == "{":
            end = text.find("}", index)
            if end < 0:
                raise ValueError(f"unterminated control in {text!r}")
            name = text[index + 1:end]
            try:
                output.extend(CONTROLS[name])
            except KeyError as exc:
                raise ValueError(f"unknown control {{{name}}}") from exc
            index = end + 1
            continue
        output.extend(encode_char(text[index], charmap))
        index += 1

    output.append(0xFF)
    if styled and len(output) > 15:
        raise ValueError(f"styled option exceeds the Japanese 15-byte stack buffer: {text!r}")
    return bytes(output)


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit("usage: build_texts.py CHARMAP TEXTS_JSON OUTPUT_INC")
    charmap_path, texts_path, output_path = map(Path, sys.argv[1:])
    charmap = read_charmap(charmap_path)
    definitions = json.loads(texts_path.read_text(encoding="utf-8"))

    lines = ["@ Generated by patch/tools/build_texts.py; do not edit.", ".align 2"]
    for definition in definitions:
        name = definition["name"]
        encoded = encode_text(definition["text"], charmap, definition.get("styled", False))
        lines.extend((f".global {name}", f"{name}:", "    .byte " + ", ".join(f"0x{x:02X}" for x in encoded)))
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
